### ISSUE TITLE
Gear missing from database

### ISSUE THREAD

**Issue by klattmose** [Leanny/splat3seedchecker#1]
Looks like the Annaki Strappy Sandals, the Dappled Hammertreads, and the Icy Down Boots are missing from the Gear Database Add New Gear form.

**Comment by Leanny** [comment]
All of them are in the list. I should probably add a name for them to make them easier searchable, but they are there for sure 

![IMG_20230605_002354](https://github.com/Leanny/splat3seedchecker/assets/1884062/30bd6b76-1efa-4a4b-a22b-4caa1831787c)

**Comment by klattmose** [comment]
So it is. I seem to be having a weirder problem. I thought they were missing because I couldn't find them with ctrl-F, and couldn't see them in the Add Gear form. Just now, I cleared the filters from the defaults and found this:

![image](https://github.com/Leanny/splat3seedchecker/assets/4196664/f2104476-dce8-4fe7-bcc4-b7382b9334d4)

I'll delete them and reupload my gear-data JSON.
