### ISSUE TITLE
Title 1 and title 2 do not match up in seed listing but they do in profile

### ISSUE THREAD

**Issue by DanteDraconi** [Leanny/splat3seedchecker#2]
![image](https://github.com/Leanny/splat3seedchecker/assets/9718875/123b5973-f67b-4f87-beed-8c4dcb850895)

![image](https://github.com/Leanny/splat3seedchecker/assets/9718875/b3d0d37b-5f54-445c-a9fd-9967c3b637a2)

Already double and triple checked that I entered all titles correctly and also made sure to count them twice (taking into account the pairs like bro/sis) so I don't get what exactly isn't matching up

It's not a big deal if I can't fix it because it was mostly curiosty about how long until I get certain titles but posting just in case there's something else going on

[gear_seed_database_2024-04-01_19-47-27.json](https://github.com/Leanny/splat3seedchecker/files/14828001/gear_seed_database_2024-04-01_19-47-27.json)

**Comment by Leanny** [comment]
The first one only contains the titles you can get via title seed (i.e. from shell out machine), the second one includes all titles you get via events (i.e. story titles, DLC, etc).
Given this info, please check the following:
Do you really own the adjective "Tailwind-Riding"?
Do you really not own the subject "Vanguard"?

If you can answer one of the two with yes, then you have an odd number of titles again and you still overlooked another one

**Comment by DanteDraconi** [comment]
Uggh... turns out I didn't have Vanguard checked and everytime I went through the list I didn't notice I was mixing up Vagabond with Vanguard! I swapped those two and managed to find my seed.

Thanks a lot for pointing it out and sorry for the confusion.
